//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mevzuuCafe.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CafeDbEntities : DbContext
    {
        public CafeDbEntities()
            : base("name=CafeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblAnasayfa> tblAnasayfa { get; set; }
        public virtual DbSet<tblGallery> tblGallery { get; set; }
        public virtual DbSet<tblHome> tblHome { get; set; }
        public virtual DbSet<tblintro> tblintro { get; set; }
        public virtual DbSet<tblMenu> tblMenu { get; set; }
        public virtual DbSet<tblPages> tblPages { get; set; }
        public virtual DbSet<tblSlider> tblSlider { get; set; }
    }
}
