//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mevzuuCafe.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHome
    {
        public int homeID { get; set; }
        public string bolum { get; set; }
        public string resim { get; set; }
        public string metin { get; set; }
        public string metin2 { get; set; }
    }
}
