//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mevzuuCafe.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblintro
    {
        public int tanitimID { get; set; }
        public string baslik { get; set; }
        public string metin { get; set; }
        public Nullable<bool> introstatus { get; set; }
    }
}
