//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mevzuuCafe.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public int menuID { get; set; }
        public string menuName { get; set; }
        public string menuContent { get; set; }
        public string menuImage { get; set; }
        public Nullable<int> menuPrice { get; set; }
        public Nullable<bool> menuStatus { get; set; }
    }
}
